"""schema_sync

Revision ID: 306b529c4d97
Revises: db977c8ad8ee
Create Date: 2026-03-21 09:28:09.588113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '306b529c4d97'
down_revision: Union[str, None] = 'db977c8ad8ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aircraft', 'state',
               existing_type=postgresql.ENUM('REGISTERED', 'EN_ROUTE_INBOUND', 'APPROACH', 'FINAL_APPROACH', 'LANDING', 'LANDED', 'TAXIING', 'PARKED', 'CHARGING', 'MAINTENANCE', 'PRE_DEPARTURE', 'TAKEOFF_READY', 'DEPARTING', 'DEPARTED', 'EMERGENCY', 'DEREGISTERED', name='aircraftstate'),
               type_=sa.Enum('REGISTERED', 'EN_ROUTE_INBOUND', 'APPROACH', 'FINAL_APPROACH', 'LANDING', 'LANDED', 'TAXIING', 'PARKED', 'CHARGING', 'MAINTENANCE', 'PRE_DEPARTURE', 'TAKEOFF_READY', 'DEPARTING', 'DEPARTED', 'EMERGENCY', 'DEREGISTERED', name='aircraft_state_enum'),
               postgresql_using='state::text::aircraft_state_enum',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aircraft', 'state',
               existing_type=sa.Enum('REGISTERED', 'EN_ROUTE_INBOUND', 'APPROACH', 'FINAL_APPROACH', 'LANDING', 'LANDED', 'TAXIING', 'PARKED', 'CHARGING', 'MAINTENANCE', 'PRE_DEPARTURE', 'TAKEOFF_READY', 'DEPARTING', 'DEPARTED', 'EMERGENCY', 'DEREGISTERED', name='aircraft_state_enum'),
               type_=postgresql.ENUM('REGISTERED', 'EN_ROUTE_INBOUND', 'APPROACH', 'FINAL_APPROACH', 'LANDING', 'LANDED', 'TAXIING', 'PARKED', 'CHARGING', 'MAINTENANCE', 'PRE_DEPARTURE', 'TAKEOFF_READY', 'DEPARTING', 'DEPARTED', 'EMERGENCY', 'DEREGISTERED', name='aircraftstate'),
               postgresql_using='state::text::aircraftstate',
               existing_nullable=False)
    # ### end Alembic commands ###
