directories:
  output: release
  buildResources: assets
appId: com.vams.app
productName: VAMS
win:
  target: nsis
  signAndEditExecutable: false
artifactName: ${productName} Setup.${ext}
files:
  - filter:
      - dist/**/*
      - electron.js
      - package.json
electronVersion: 40.8.0
